    
name: Theme Name
description: This is the Theme Name theme built using the Radius template language for CleanSlate. Originally authored by Adam Johnson.

# CSS
css: 
  
  # Turn CSS compression/minification on/off.
  compress: false
  
# JavaScript options
js:
  
  # Turn JavaScript compression/minification on/off
  compress: false
  
  # Turn JavaScript mangling on/off.
  mangle: true