    
name: Information Technology
description: This is the Information Technology theme built using the Radius template language for CleanSlate. Originally authored by Adam Glenn.

# CSS
css: 
  
  # Turn CSS compression/minification on/off.
  compress: true
  
# JavaScript options
js:
  
  # Turn JavaScript compression/minification on/off
  compress: false
  
  # Turn JavaScript mangling on/off.
  mangle: true